"""Add question_set field to questions table

Revision ID: bfcb0e742b83
Revises: b6b6f926d575
Create Date: 2025-11-21 22:47:34.093213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfcb0e742b83'
down_revision: Union[str, Sequence[str], None] = 'b6b6f926d575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_set', sa.String(length=100), nullable=True))
    op.alter_column('responses', 'selected_option_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_results_id'), table_name='responses')
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    op.drop_constraint(op.f('results_question_id_fkey'), 'responses', type_='foreignkey')
    op.drop_constraint(op.f('results_user_id_fkey'), 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'responses', 'questions', ['question_id'], ['id'])
    op.drop_column('responses', 'deleted_at')
    op.drop_column('responses', 'updated_at')
    op.drop_column('responses', 'readlater_flag')
    op.drop_column('responses', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('readlater_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key(op.f('results_user_id_fkey'), 'responses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('results_question_id_fkey'), 'responses', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.create_index(op.f('ix_results_id'), 'responses', ['id'], unique=False)
    op.alter_column('responses', 'selected_option_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('questions', 'question_set')
    # ### end Alembic commands ###
